//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Popcorn.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Popcorn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        public static string AboutLabel {
            get {
                return ResourceManager.GetString("AboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actors.
        /// </summary>
        public static string ActorsLabel {
            get {
                return ResourceManager.GetString("ActorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All.
        /// </summary>
        public static string AllLabel {
            get {
                return ResourceManager.GetString("AllLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A new update is applying... %PERCENTAGE% done..
        /// </summary>
        public static string ApplyingUpdate {
            get {
                return ResourceManager.GetString("ApplyingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Average.
        /// </summary>
        public static string AverageLabel {
            get {
                return ResourceManager.GetString("AverageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bad.
        /// </summary>
        public static string BadLabel {
            get {
                return ResourceManager.GetString("BadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Big.
        /// </summary>
        public static string Big {
            get {
                return ResourceManager.GetString("Big", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bigger.
        /// </summary>
        public static string Bigger {
            get {
                return ResourceManager.GetString("Bigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Buffering.
        /// </summary>
        public static string BufferingLabel {
            get {
                return ResourceManager.GetString("BufferingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cache size (in MB).
        /// </summary>
        public static string CacheSizeLabel {
            get {
                return ResourceManager.GetString("CacheSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to cast media..
        /// </summary>
        public static string CastFailed {
            get {
                return ResourceManager.GetString("CastFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cast.
        /// </summary>
        public static string CastLabel {
            get {
                return ResourceManager.GetString("CastLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cast to.
        /// </summary>
        public static string CastToLabel {
            get {
                return ResourceManager.GetString("CastToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change location.
        /// </summary>
        public static string ChangeLocation {
            get {
                return ResourceManager.GetString("ChangeLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a Chromecast.
        /// </summary>
        public static string ChooseChromecastLabel {
            get {
                return ResourceManager.GetString("ChooseChromecastLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a subtitle.
        /// </summary>
        public static string ChooseSubtitleLabel {
            get {
                return ResourceManager.GetString("ChooseSubtitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear.
        /// </summary>
        public static string ClearButton {
            get {
                return ResourceManager.GetString("ClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        public static string CloseLabel {
            get {
                return ResourceManager.GetString("CloseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collections.
        /// </summary>
        public static string CollectionsLabel {
            get {
                return ResourceManager.GetString("CollectionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm password....
        /// </summary>
        public static string ConfirmPasswordWatermark {
            get {
                return ResourceManager.GetString("ConfirmPasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CONNECTING TO CHROMECAST.
        /// </summary>
        public static string ConnectingToChomecastLabel {
            get {
                return ResourceManager.GetString("ConnectingToChomecastLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You seem to have an internet connection error. Please retry..
        /// </summary>
        public static string ConnectionErrorDescriptionPopup {
            get {
                return ResourceManager.GetString("ConnectionErrorDescriptionPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Internet connection error.
        /// </summary>
        public static string ConnectionErrorLabel {
            get {
                return ResourceManager.GetString("ConnectionErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Currently playing.
        /// </summary>
        public static string CurrentlyPlayingLabel {
            get {
                return ResourceManager.GetString("CurrentlyPlayingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Custom.
        /// </summary>
        public static string CustomLabel {
            get {
                return ResourceManager.GetString("CustomLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default quality.
        /// </summary>
        public static string DefaultQualityLabel {
            get {
                return ResourceManager.GetString("DefaultQualityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default subtitle language.
        /// </summary>
        public static string DefaultSubtitleLanguageLabel {
            get {
                return ResourceManager.GetString("DefaultSubtitleLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Directors.
        /// </summary>
        public static string DirectorsLabel {
            get {
                return ResourceManager.GetString("DirectorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Discover.
        /// </summary>
        public static string DiscoverTitleTab {
            get {
                return ResourceManager.GetString("DiscoverTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dismiss.
        /// </summary>
        public static string Dismiss {
            get {
                return ResourceManager.GetString("Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Downloading subtitles....
        /// </summary>
        public static string DownloadingSubtitlesLabel {
            get {
                return ResourceManager.GetString("DownloadingSubtitlesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A new update is downloading... %PERCENTAGE% done..
        /// </summary>
        public static string DownloadingUpdate {
            get {
                return ResourceManager.GetString("DownloadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download.
        /// </summary>
        public static string DownloadLabel {
            get {
                return ResourceManager.GetString("DownloadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download limit (kB/s).
        /// </summary>
        public static string DownloadLimitLabel {
            get {
                return ResourceManager.GetString("DownloadLimitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An issue has occurred while processing the dropped file..
        /// </summary>
        public static string DroppedFileIssue {
            get {
                return ResourceManager.GetString("DroppedFileIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email....
        /// </summary>
        public static string EmailWatermark {
            get {
                return ResourceManager.GetString("EmailWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à That&apos;s embarrassing....
        /// </summary>
        public static string EmbarrassingError {
            get {
                return ResourceManager.GetString("EmbarrassingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No movie found.
        /// </summary>
        public static string EmptyMovieSearchLabel {
            get {
                return ResourceManager.GetString("EmptyMovieSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No show found.
        /// </summary>
        public static string EmptyShowSearchLabel {
            get {
                return ResourceManager.GetString("EmptyShowSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Episodes.
        /// </summary>
        public static string EpisodesLabel {
            get {
                return ResourceManager.GetString("EpisodesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed loading.
        /// </summary>
        public static string FailedLoadingLabel {
            get {
                return ResourceManager.GetString("FailedLoadingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A critical error has occured. You should restart the app immediately..
        /// </summary>
        public static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Favorites.
        /// </summary>
        public static string FavoritesTitleTab {
            get {
                return ResourceManager.GetString("FavoritesTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First name....
        /// </summary>
        public static string FirstNameWatermark {
            get {
                return ResourceManager.GetString("FirstNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Genres.
        /// </summary>
        public static string GenresLabel {
            get {
                return ResourceManager.GetString("GenresLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Good.
        /// </summary>
        public static string GoodLabel {
            get {
                return ResourceManager.GetString("GoodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Greatest.
        /// </summary>
        public static string GreatestTitleTab {
            get {
                return ResourceManager.GetString("GreatestTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Health.
        /// </summary>
        public static string HealthLabel {
            get {
                return ResourceManager.GetString("HealthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help.
        /// </summary>
        public static string HelpLabel {
            get {
                return ResourceManager.GetString("HelpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ignore.
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations.
        /// </summary>
        public static string InformationsLabel {
            get {
                return ResourceManager.GetString("InformationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last name....
        /// </summary>
        public static string LastNameWatermark {
            get {
                return ResourceManager.GetString("LastNameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Later.
        /// </summary>
        public static string LaterLabel {
            get {
                return ResourceManager.GetString("LaterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à License.
        /// </summary>
        public static string LicenseLabel {
            get {
                return ResourceManager.GetString("LicenseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DISCOVERING CHROMECASTS....
        /// </summary>
        public static string LoadingChromecastsLabel {
            get {
                return ResourceManager.GetString("LoadingChromecastsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading trailer....
        /// </summary>
        public static string LoadingTrailerLabel {
            get {
                return ResourceManager.GetString("LoadingTrailerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You are already logged in..
        /// </summary>
        public static string LoggedInLabel {
            get {
                return ResourceManager.GetString("LoggedInLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        public static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quality.
        /// </summary>
        public static string MovieQualityLabel {
            get {
                return ResourceManager.GetString("MovieQualityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string MovieSettingsLabel {
            get {
                return ResourceManager.GetString("MovieSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Movies.
        /// </summary>
        public static string MoviesLabel {
            get {
                return ResourceManager.GetString("MoviesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à movies.
        /// </summary>
        public static string MoviesWord {
            get {
                return ResourceManager.GetString("MoviesWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A new update has been applied. Would you like to restart now?.
        /// </summary>
        public static string NewUpdateDescriptionLabel {
            get {
                return ResourceManager.GetString("NewUpdateDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New update.
        /// </summary>
        public static string NewUpdateLabel {
            get {
                return ResourceManager.GetString("NewUpdateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à NO CHROMECAST AVAILABLE.
        /// </summary>
        public static string NoChromecastLabel {
            get {
                return ResourceManager.GetString("NoChromecastLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is no media file in the torrent you dropped in the UI..
        /// </summary>
        public static string NoMediaInDroppedTorrent {
            get {
                return ResourceManager.GetString("NoMediaInDroppedTorrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is no media file in the torrent..
        /// </summary>
        public static string NoMediaInTorrent {
            get {
                return ResourceManager.GetString("NoMediaInTorrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        public static string NoneLabel {
            get {
                return ResourceManager.GetString("NoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No similar movie found.
        /// </summary>
        public static string NoSimilarLabel {
            get {
                return ResourceManager.GetString("NoSimilarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Now.
        /// </summary>
        public static string NowLabel {
            get {
                return ResourceManager.GetString("NowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Off.
        /// </summary>
        public static string OffLabel {
            get {
                return ResourceManager.GetString("OffLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à of.
        /// </summary>
        public static string OfWord {
            get {
                return ResourceManager.GetString("OfWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On.
        /// </summary>
        public static string OnLabel {
            get {
                return ResourceManager.GetString("OnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OPTIONS.
        /// </summary>
        public static string OptionsLabel {
            get {
                return ResourceManager.GetString("OptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password....
        /// </summary>
        public static string PasswordWatermark {
            get {
                return ResourceManager.GetString("PasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Peers.
        /// </summary>
        public static string PeersLabel {
            get {
                return ResourceManager.GetString("PeersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Playing.
        /// </summary>
        public static string PlayingTitleTab {
            get {
                return ResourceManager.GetString("PlayingTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Play.
        /// </summary>
        public static string PlayLabel {
            get {
                return ResourceManager.GetString("PlayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Popular.
        /// </summary>
        public static string PopularShowTitleTab {
            get {
                return ResourceManager.GetString("PopularShowTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Popular.
        /// </summary>
        public static string PopularTitleTab {
            get {
                return ResourceManager.GetString("PopularTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quality.
        /// </summary>
        public static string QualityLabel {
            get {
                return ResourceManager.GetString("QualityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rating.
        /// </summary>
        public static string RatingLabel {
            get {
                return ResourceManager.GetString("RatingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recent.
        /// </summary>
        public static string RecentTitleTab {
            get {
                return ResourceManager.GetString("RecentTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recommendations.
        /// </summary>
        public static string RecommendationsTitleTab {
            get {
                return ResourceManager.GetString("RecommendationsTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh.
        /// </summary>
        public static string RefreshLabel {
            get {
                return ResourceManager.GetString("RefreshLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reload.
        /// </summary>
        public static string ReloadLabel {
            get {
                return ResourceManager.GetString("ReloadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remaining Time.
        /// </summary>
        public static string RemainingLabel {
            get {
                return ResourceManager.GetString("RemainingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restart.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search....
        /// </summary>
        public static string SearchBoxWatermark {
            get {
                return ResourceManager.GetString("SearchBoxWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        public static string SearchTitleTab {
            get {
                return ResourceManager.GetString("SearchTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Seeders.
        /// </summary>
        public static string SeedersLabel {
            get {
                return ResourceManager.GetString("SeedersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Seen.
        /// </summary>
        public static string SeenTitleTab {
            get {
                return ResourceManager.GetString("SeenTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string SettingsMenuTitle {
            get {
                return ResourceManager.GetString("SettingsMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shows.
        /// </summary>
        public static string ShowsLabel {
            get {
                return ResourceManager.GetString("ShowsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à shows.
        /// </summary>
        public static string ShowsWord {
            get {
                return ResourceManager.GetString("ShowsWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Similar.
        /// </summary>
        public static string SimilarLabel {
            get {
                return ResourceManager.GetString("SimilarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Small.
        /// </summary>
        public static string Small {
            get {
                return ResourceManager.GetString("Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Smaller.
        /// </summary>
        public static string Smaller {
            get {
                return ResourceManager.GetString("Smaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à (kB/s).
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop.
        /// </summary>
        public static string StopLabel {
            get {
                return ResourceManager.GetString("StopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subtitles color.
        /// </summary>
        public static string SubtitlesColorLabel {
            get {
                return ResourceManager.GetString("SubtitlesColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subtitles.
        /// </summary>
        public static string SubtitlesLabel {
            get {
                return ResourceManager.GetString("SubtitlesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subtitle size.
        /// </summary>
        public static string SubtitlesSizeLabel {
            get {
                return ResourceManager.GetString("SubtitlesSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trailer.
        /// </summary>
        public static string TrailerButton {
            get {
                return ResourceManager.GetString("TrailerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The trailer is not available for the current language..
        /// </summary>
        public static string TrailerNotAvailable {
            get {
                return ResourceManager.GetString("TrailerNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown.
        /// </summary>
        public static string UnknownLabel {
            get {
                return ResourceManager.GetString("UnknownLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A new update has been applied..
        /// </summary>
        public static string UpdateApplied {
            get {
                return ResourceManager.GetString("UpdateApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Updated.
        /// </summary>
        public static string UpdatedTitleTab {
            get {
                return ResourceManager.GetString("UpdatedTitleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Release informations:.
        /// </summary>
        public static string UpdateReleasesInformationsLabel {
            get {
                return ResourceManager.GetString("UpdateReleasesInformationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Upload.
        /// </summary>
        public static string UploadLabel {
            get {
                return ResourceManager.GetString("UploadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Upload limit (kB/s).
        /// </summary>
        public static string UploadLimitLabel {
            get {
                return ResourceManager.GetString("UploadLimitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Username....
        /// </summary>
        public static string UsernameWatermark {
            get {
                return ResourceManager.GetString("UsernameWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version history.
        /// </summary>
        public static string VersionHistoryLabel {
            get {
                return ResourceManager.GetString("VersionHistoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Very bad.
        /// </summary>
        public static string VeryBadLabel {
            get {
                return ResourceManager.GetString("VeryBadLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Very good.
        /// </summary>
        public static string VeryGoodLabel {
            get {
                return ResourceManager.GetString("VeryGoodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Watch.
        /// </summary>
        public static string WatchButton {
            get {
                return ResourceManager.GetString("WatchButton", resourceCulture);
            }
        }
    }
}
